services:
  - type: web
    name: ai-diet-plan-generator
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
